import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { getWordDataRequest } from "../features/wordData/api";
import { WordData } from "../features/wordData/types";

const Home: NextPage = () => {
    const [wordData, setWordData] = useState<WordData | null>(null);
    const [word, setWord] = useState<string>("");

    const fetchWordData = async () => {
        try {
            const newWordData = await getWordDataRequest(word);

            setWordData(newWordData);
        } catch (err) {
            console.log(err);
        }
    };

    const handleRequestWordData = (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        fetchWordData();
    };

    return (
        <>
            <Head>
                <title>Word Data</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <form onSubmit={handleRequestWordData}>
                <input value={word} onChange={(e) => setWord(e.target.value)} />
                <button>Show word data</button>
            </form>
        </>
    );
};

export default Home;
